version: "3.3"
services:
  postgres_register:
    container_name: postgres_register
    image: postgres:12.2
    environment:
      - POSTGRES_USER=register
      - POSTGRES_PASSWORD=register
    ports:
      - 5432:5432