version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
     POSTGRES_PASSWORD: "admin123"
    ports:
      - "5432:5432"
    volumes:
      - ./PostgreSQL/ifood:/var/lib/postgresql/data
      - ./PostgreSQL/init-database:/docker-entrypoint-initdb.d/
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "wilbur.dev@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
